### ISSUE TITLE
Add Logo Image As Header

### ISSUE THREAD

**Issue by yaroslavpaz** [EvotecIT/PSWritePDF#31] opened 2021-12-04 14:44 UTC
Hi There!
When will this function be added: 
Add Logo Image As Header in the PDF
There is currently no way to do it.
Thank you!
Yaro

**Comment by PrzemyslawKlys** [comment] 2021-12-04 15:31
Duplicate of https://github.com/EvotecIT/PSWritePDF/issues/11 right?

**Comment by yaroslavpaz** [comment] 2021-12-04 15:46
yeah, with some nuances, that one was requested more than a year ago, no time frame yet?

**Comment by PrzemyslawKlys** [comment] 2021-12-04 15:49
Well

```powershell
New-PDF -MarginLeft 20 { #520 -MarginRight 20 -MarginTop 20 -MarginBottom 20 -PageSize B4 -Rotate {
    New-PDFImage -ImagePath "$PSScriptRoot\Evotec-Logo-600x190.png" -BackgroundColor Red -BackgroundColorOpacity 0.5
    New-PDFText -Text 'Test ', 'Me', 'Oooh' -FontColor BLUE, YELLOW, RED
    New-PDFList {
        New-PDFListItem -Text 'Test'
        New-PDFListItem -Text '2nd'
    }
} -FilePath "$PSScriptRoot\Example09-Images01.pdf" -Show
```

![image](https://user-images.githubusercontent.com/15063294/144715779-3db719ac-de2d-4613-bed0-42fe6ffb7945.png)

```powershell
New-PDF -MarginLeft 20 { #520 -MarginRight 20 -MarginTop 20 -MarginBottom 20 -PageSize B4 -Rotate {
    New-PDFImage -ImagePath "$PSScriptRoot\Evotec-Logo-600x190.png" -BackgroundColor Red -BackgroundColorOpacity 0.5
    New-PDFImage -ImagePath "$PSScriptRoot\Evotec-Logo-600x190.png"
    New-PDFText -Text 'Test ', 'Me', 'Oooh' -FontColor BLUE, YELLOW, RED
    New-PDFList {
        New-PDFListItem -Text 'Test'
        New-PDFListItem -Text '2nd'
    }
} -FilePath "$PSScriptRoot\Example09-Images01.pdf" -Show
```

![image](https://user-images.githubusercontent.com/15063294/144715806-4505788e-85d9-4971-8e90-a9895864936a.png)

Probably needs some more options for image. Not sure if/when to release it.

**Comment by yaroslavpaz** [comment] 2021-12-04 18:00
Wow, That looks beautiful!
Can you share me the module or add it to prerelease please?

**Comment by yaroslavpaz** [comment] 2021-12-13 20:57
Hi bro, got last message? please I need it bad, thanks in advance, God bless you!

**Comment by PrzemyslawKlys** [comment] 2021-12-20 17:59
Will be in next version

**Closed by PrzemyslawKlys** 2021-12-20 17:59 UTC
